version: '3'
name: 'docker-toni-josep'

services:
  # Frontend: Pàgines estàtiques servides per Apache
  apache:
    image: httpd:2.4
    ports:
      - 80:80
    volumes:
      - ./wordsearch_front:/usr/local/apache2/htdocs/

  # Backend: API REST en Node.js (us la passarem aqui)
  node:
    image: node:16
    expose:
      - 3000
    ports:
      - 3000:3000
    working_dir: /home/node/app
    volumes:
      - ./wordsearch_back:/home/node/app
    command: "npm start"

  # Base de dades (MariaDB):
  db:
    image: mariadb:10.7
    environment:
      - MYSQL_ROOT_PASSWORD=cifproot
      - MYSQL_DATABASE=practicadaw
    volumes:
      - ./volums/mysql:/var/lib/mysql
    expose:
      - 3306

  # phpMyAdmin:
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=db
    ports:
      - 8083:80
    depends_on:
      - db
